### ISSUE TITLE
Activity & WebSocket feature's RFC

### ISSUE THREAD

**Issue by dnacu** [woowa-techcamp-2020/todo-14#41]
# Activity

`cardId / columnId / from / to`

### 카드가 컬럼에 추가되었습니다.
`cardId / null / null / toColumnId` 
### 컬럼이 추가되었습니다.
`null / columnId / null / null`

### 컬럼에서 카드가 삭제되었습니다.
`cardId / null / fromColumnId / null` 
### 컬럼이 삭제되었습니다.
`null / columnId / null / null`

### 카드의 내용이 A에서 B로 수정되었습니다.
`cardId / null / fromContent / toContent` 
### 컬럼의 제목이 A에서 B로 수정되었습니다.
`null / columnId / fromTitle / toTitle`

### 카드가 컬럼 A에서 컬럼 B로 이동되었습니다. (같은 컬럼이면 그냥 prev===next)
`cardId / null / fromColumId / toColumnId` 
### 컬럼이 이동되었습니다.
`null / columnId / fromPreviousColumnId / toPreviousColumnId`

**Comment by dnacu** [comment]
👍

**Comment by jhaemin** [comment]
🙆‍♂️
